function [fitresult, gof] = createT1_Fit(TI_vect_repeat, T1_vect)
%CREATEFIT(TI_VECT_REPEAT,T1_VECT)
%  Create a fit.
%
%  Data for 'untitled fit 6' fit:
%      X Input : TI_vect_repeat
%      Y Output: T1_vect
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Oct-2017 16:57:40


%% Fit: 'untitled fit 6'.
[xData, yData] = prepareCurveData( TI_vect_repeat, T1_vect );

% Set up fittype and options.
ft = fittype( 'abs(a*(1-b*exp(-x/c)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
%opts.Lower = [10000 -Inf -Inf];
%opts.StartPoint = [15000 20 1500];


opts.Lower = [5000 -Inf -Inf];
opts.StartPoint = [15000 20 1500];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

T1_str=num2str(fitresult.c/1000);
T1_string=['T1 (s) ' T1_str];


% Plot fit with data.
%figure( 'Name', 'T1 fitting' );
%h = plot( fitresult, xData, yData );


%rmse_str=num2str(gof.rmse);
%rmse_string=['RMSE ' rmse_str]; 

%legend( h, T1_string, rmse_string, 'Location', 'NorthEast' );

% Label axes 
%xlabel TI(s)
%ylabel Mz
%grid on


